version: "3"

services:
  bierproductie_api:
    container_name: bierproductie_api
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: uvicorn --reload bierproductie_api.asgi:app --port 8000 --host 0.0.0.0
    environment:
      - POSTGRES_HOST=bierproductie_api_db
    depends_on:
      - bierproductie_api_db
    ports:
      - 11001:8000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    networks:
      - bierproductie_api_internal
  bierproductie_api_db:
    image: postgres:12-alpine
    container_name: bierproductie_api_db
    env_file:
      - .env
    networks:
      - bierproductie_api_internal

networks:
  bierproductie_api_internal:
